language: cpp

compiler:
  - clang
  - gcc

sudo: false

os:
  - linux
  - osx

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install gettext; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew link gettext --force; fi

script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then autoreconf --install --force --verbose && ./configure && make && make check; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then autoreconf --install --force --verbose && ./configure && make; fi

addons:
  apt:
    packages:
    - autoconf
    - automake
    - autopoint
